/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "Quiet sm_cvar",
	author = "IBeMad",
	description = "SM_Cvar command without any return on success.",
	version = "1.0",
	url = "bit.ly/ch1ckenscoop"
}

public OnPluginStart()
{
	RegServerCmd("sm_qcvar", Command_Cvar)
}

public Action:Command_Cvar(args)
{
	new Handle:g_hCvarToChange
	new String:cvar[192]
	new String:arg[192]
	
	//Check early on if we have too many or too few args
	if (GetCmdArgs() != 2)
	{
		PrintToServer("Format: 'sm_qcvar <cvar> <value>'");
		return Plugin_Handled
	}
	
	GetCmdArg(1, cvar, sizeof(cvar));
	GetCmdArg(2, arg, sizeof(arg));
	
	g_hCvarToChange = FindConVar(cvar)
	if(g_hCvarToChange == INVALID_HANDLE)
	{
		PrintToServer("[QCvar] Unable to hook cvar '%s'.", cvar);
		return Plugin_Handled
	}
	else
	{
		SetConVarString(g_hCvarToChange, arg)
	}
 
	return Plugin_Handled
}